'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const icons={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',factory:'<path d="M3 21V10l6 3V8l6 4V3h4l2 18H3Z"/><path d="M7 17h1m4 0h1m4 0h1"/>',sliders:'<path d="M4 6h9m4 0h3M4 12h3m4 0h9M4 18h10m4 0h2"/><circle cx="15" cy="6" r="2"/><circle cx="9" cy="12" r="2"/><circle cx="16" cy="18" r="2"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4V3Z"/>',book:'<path d="M12 5v16M3 3c4-1 7 0 9 2 2-2 5-3 9-2v16c-4-1-7 0-9 2-2-2-5-3-9-2V3Z"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',phone:'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4m0 3h.01"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',arrow:'<path d="M4 12h15m-5-5 5 5-5 5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.book}</svg>`;
$$('[data-icon]').forEach(e=>e.outerHTML=icon(e.dataset.icon));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFKC').toLowerCase().replace(/[\s·ㆍᆞ.,()（）\[\]\-]/g,'');
const aliases={nox:'질소산화물',no2:'질소산화물',sox:'황산화물',so2:'황산화물',nh3:'암모니아',hcl:'염화수소',co:'일산화탄소',thc:'탄화수소',포름알데하이드:'포름알데히드',소각시설:'소각',보일러:'보일러'};
let data, view='standards', query='', source='all', era='current', category='all', limit=8, selected=null, selectedPage=1, deferredInstall=null;
let saved=[];try{saved=JSON.parse(localStorage.getItem('aircode.saved.v1')||'[]');if(!Array.isArray(saved))saved=[];}catch{}
let allRecords=[],byId=new Map(),toastTimer;
const labels={methods:'공정시험기준',pollutants:'대기오염물질',search:'통합 검색',facilities:'배출시설 찾기',standards:'배출허용기준',saved:'내 보관함',sources:'원문 자료실'};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2400)}
function updateCount(){$('#saved-count').textContent=saved.length}
function tokens(q){return q.trim().split(/\s+/).filter(Boolean).map(t=>norm(aliases[t.toLowerCase()]||t))}
function highlight(text){const words=query.trim().split(/\s+/).filter(Boolean).map(t=>aliases[t.toLowerCase()]||t);let html=esc(text);for(const w of words){if(!w)continue;const p=esc(w).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');try{html=html.replace(new RegExp(p,'gi'),m=>`<mark>${m}</mark>`)}catch{}}return html}
function snippet(r){let text=r.text.replace(/\n/g,' ');const first=query.trim().split(/\s+/)[0];if(first){const word=aliases[first.toLowerCase()]||first;const at=text.toLowerCase().indexOf(word.toLowerCase());if(at>70)text='… '+text.slice(at-45)}return text.slice(0,240)}
function filtered(){const ts=tokens(query);let list=allRecords.filter(r=>{
 if(!numericMatches(r))return false;
 if(source!=='all'&&r.annex!==Number(source))return false;
 if(era!=='all'&&!r.eras.includes(era))return false;
 if(category!=='all'&&r.category!==category&&!(r.annex===8&&((r.page===39&&category==='가스')||(r.page===50&&['입자','비고'].includes(category)))))return false;
 // Structured facility records retain complete multi-page conditions; page records retain all notes.
 if(r.annex===3&&r.kind==='page'&&r.eras.length===1&&r.eras[0]==='current'&&r.page>=13&&r.page<=26)return false;
 const hay=norm(r.title+' '+(r.keywords||'')+' '+r.text);return ts.every(t=>hay.includes(t));
 });
 if($('#sort').value==='source')return list.sort((a,b)=>a.annex-b.annex||a.page-b.page||(a.number||0)-(b.number||0));
 const priority={f32:100,f35:95,f29:90,f30:85,f21:80,f1:75};
 return list.sort((a,b)=>{const score=r=>ts.length?ts.reduce((n,t)=>n+(norm(r.title).includes(t)?20:0)+(norm(r.keywords||'').includes(t)?6:0),0)+(r.kind==='facility'?2:0):numericScore(r)||priority[r.id]||0;return score(b)-score(a)||a.annex-b.annex||a.page-b.page});
}
function card(r){if(r.kind==='standard')return numericCard(r);const isSaved=saved.includes(r.id),f=r.kind==='facility';return `<article class="card"><div class="card-top"><span class="badge ${r.annex===8?'standard':''}">${r.annex===3?'배출시설':'배출허용기준'}</span><span class="source-ref">별표 ${r.annex} · ${r.pages.length>1?r.pages[0]+'–'+r.pages.at(-1):r.page}쪽</span><button class="bookmark" data-save="${r.id}" aria-label="${esc(r.title)} ${isSaved?'보관 해제':'보관'}" aria-pressed="${isSaved}">${icon('bookmark')}</button></div><button class="card-title" data-open="${r.id}">${f?`<span class="record-number">${String(r.number).padStart(2,'0')}</span>`:''}${highlight(r.title)}</button><p class="card-snippet">${highlight(snippet(r))}</p><div class="card-bottom"><div class="tags"><span>${r.eras.includes('past')&&!r.eras.includes('current')?'2019년까지 적용':'2020년 이후 기준'}</span><span>${f?'대상 · 규모 기준':r.category==='시설'?'적용기준 · 비고':r.category==='특례'?'특례':'원문 표 · '+r.category}</span></div><button class="detail-link" data-open="${r.id}">조건·원문 보기 <span>↗</span></button></div></article>`}
function render(){if(!data)return;if(view==='methods'){renderMethods();return}if(view==='pollutants'){renderCatalog();return}updateCount();if(view==='saved'){renderSaved();return}if(view==='sources')return;updateNumericControls();const results=filtered();$('#result-heading').textContent=query?`“${query}” 검색 결과`:source==='3'?'배출시설 목록':source==='8'?'배출허용기준 목록':'전체 자료';$('#result-count').textContent=`${results.length}건`;if(source==='8'&&era!=='past'&&!['비고','특례'].includes(category)&&!query)$('#result-heading').textContent=pollutantFilter==='all'?'조건별 배출허용기준':pollutantFilter+' 배출허용기준';$('#active-filters').innerHTML=`<span class="filter-chip">${era==='current'?'2020년 이후 적용':era==='past'?'2019년까지 적용':'모든 적용 시기'}</span>${source!=='all'?`<span class="filter-chip">별표 ${source}</span>`:''}${category!=='all'?`<span class="filter-chip">${esc(category)}</span>`:''}`;if(renderGroupedStandards(results))return;$('#results').innerHTML=results.length?results.slice(0,limit).map(card).join(''):`<div class="empty">${icon('search')}<h3>일치하는 항목이 없습니다</h3><p>시설명을 짧게 입력하거나 검색 범위를 넓혀보세요.<br>예: ‘소각’, ‘보일러’, ‘질소산화물’</p><button data-reset>전체 자료 보기</button></div>`;$('#load-more').hidden=results.length<=limit;$('#load-more').innerHTML=`결과 더 보기 <span>${Math.min(limit,results.length)} / ${results.length}</span>`;}
function syncFilters(){for(const n of ['source','era'])$$(`input[name=${n}]`).forEach(e=>e.checked=e.value===(n==='source'?source:era));$('#category').value=category;$('#query').value=query;$('#type-filter').hidden=source==='3'}
function urlState(){if(view==='methods'){methodUrl();return;}const p=new URLSearchParams();if(query)p.set('q',query);if(source!=='all')p.set('source',source);if(era!=='current')p.set('era',era);if(category!=='all')p.set('type',category);if(pollutantFilter!=='all')p.set('pollutant',pollutantFilter);if(regimeFilter!=='general')p.set('regime',regimeFilter);if(catalogLink)p.set('catalog',catalogLink);const hash=view+(p.toString()?'?'+p.toString():'');history.replaceState(null,'','#'+hash)}
function navigate(next,{q='',keep=false}={}){clearTimeout(debounce);view=labels[next]?next:'search';if(!keep){catalogLink=null;pollutantFilter='all';regimeFilter='general';$('#pollutant').value='all';$('#regime').value='general';query=q;source=view==='facilities'?'3':view==='standards'?'8':'all';era='current';category='all';limit=8}$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#breadcrumb').textContent=labels[view];$('#page-title').innerHTML=({methods:'공정시험기준, <span>쉽게 찾기.</span>',pollutants:'대기오염물질, <span>한눈에.</span>',search:'필요한 기준, <span>명확하게.</span>',facilities:'우리 시설, <span>어디에 해당할까?</span>',standards:'배출 기준을 <span>원문과 함께.</span>',saved:'자주 찾는 기준, <span>한곳에.</span>',sources:'검색의 근거가 되는 <span>원문.</span>'})[view];$('#page-description').textContent=({methods:'물질명과 ES 번호로 시험방법을 찾아보세요.',pollutants:'물질의 법령상 분류를 확인하고 배출허용기준으로 바로 이동하세요.',search:'시설명이나 오염물질로 검색하고, 적용 조건과 원문을 함께 확인하세요.',facilities:'시설 분류와 규모 조건을 찾고, 제외 사항과 비고까지 확인하세요.',standards:'오염물질·시설명을 함께 입력해 관련 기준 페이지를 찾아보세요.',saved:'이 기기에 저장한 항목입니다. 다른 기기와 자동으로 동기화되지 않습니다.',sources:'첨부된 문서 전체를 열람하고, 현행 법령과 비교하세요.'})[view];$('#search-workspace').hidden=['saved','sources','pollutants','methods'].includes(view);$('#methods-view').hidden=view!=='methods';$('#pollutants-view').hidden=view!=='pollutants';$('#sources-view').hidden=view!=='sources';$('#saved-view').hidden=view!=='saved';syncFilters();if(view==='sources')renderSources();else render();urlState();}
function doSearch(q){clearTimeout(debounce);query=q.trim();limit=8;$('#query').value=query;render();urlState()}
function reset(){catalogLink=null;pollutantFilter='all';regimeFilter='general';$('#pollutant').value='all';$('#regime').value='general';query='';era='current';category='all';source=view==='facilities'?'3':view==='standards'?'8':'all';limit=8;syncFilters();render();urlState()}
function toggleSaved(id){if(!byId.has(id))return;const was=saved.includes(id);saved=was?saved.filter(x=>x!==id):[...saved,id];try{localStorage.setItem('aircode.saved.v1',JSON.stringify(saved));toast(was?'보관함에서 제거했습니다':'이 기기의 보관함에 저장했습니다')}catch{toast('브라우저 저장 공간을 사용할 수 없어 이번 실행에서만 보관합니다')}render();$$(`[data-save="${id}"]`).forEach(b=>{b.setAttribute('aria-pressed',!was);if(b.classList.contains('button'))b.innerHTML=icon('bookmark')+(!was?'보관됨':'보관하기');else b.setAttribute('aria-label',`${byId.get(id).title} ${!was?'보관 해제':'보관'}`)})}
function renderSaved(){const list=saved.map(id=>byId.get(id)).filter(Boolean);$('#saved-view').innerHTML=list.length?`<div class="result-top"><h2>보관한 항목 <span>${list.length}</span></h2></div>`+list.map(card).join(''):`<div class="empty">${icon('bookmark')}<h3>다시 볼 기준을 모아두세요</h3><p>검색 결과의 보관 아이콘을 누르면<br>이 기기에서 빠르게 다시 찾을 수 있습니다.</p><button data-view="search">기준 검색하기</button></div>`}
function renderSources(){$('#sources-view').innerHTML=`<div class="source-grid">${data.documents.map(d=>`<article class="document-card"><div class="doc-number">ANNEX ${String(d.annex).padStart(2,'0')}</div><h2>${d.annex===3?'대기오염물질 배출시설':'대기오염물질의 배출허용기준'}</h2><p>${d.annex===3?'제5조 관련 · 시설 분류, 규모 및 적용 제외':'제15조·제33조 관련 · 물질별 기준, 비고 및 특례'}<br>개정 ${d.revision} · ${d.count}페이지</p><button class="button" data-open="p${d.annex}-1">원문 열람 ${icon('arrow')}</button><a class="button secondary" href="${d.file}" download>PDF 저장</a></article>`).join('')}</div><div class="source-grid catalog-source-cards">${pollutantCatalog.map(d=>`<article class="document-card"><h2>${d.annex===1?'대기오염물질':'특정대기유해물질'}</h2><p>별표 ${d.annex} · ${d.items.length}개 물질<br>${d.revision?'첨부본 개정 '+d.revision:'첨부본에 개정일 표기 없음'}</p><button class="button" data-view="pollutants">물질 목록 보기</button><a class="button secondary" href="${d.file}" target="_blank" rel="noopener">PDF 원문 ↗</a></article>`).join('')}</div><div class="source-detail"><button class="button" data-view="methods">공정시험기준 160개 보기 →</button></div><div class="source-detail"><strong>문서의 적용 시기를 확인하세요.</strong><p>두 문서에는 2019년까지 적용하는 기준과 2020년 이후 적용하는 기준이 함께 실려 있습니다. 검색은 2020년 이후 기준을 기본으로 하며, 과거 기준도 필터를 바꿔 검색할 수 있습니다.</p><p>배출허용기준은 수치·단위·표준산소농도와 시설 조건을 분리해 보여줍니다. 설치 시기, 시설 규모, 연료와 표준산소농도, 별도 적용 기준 및 비고를 함께 확인하세요. 시설명으로 연결한 결과는 관련 문서 검색이며, 해당 시설에 적용되는 기준을 자동으로 확정하지 않습니다.</p><a class="button secondary" href="https://www.law.go.kr/법령/대기환경보전법시행규칙" target="_blank" rel="noopener">현행 법령 확인 ↗</a></div>`}
function relatedWords(r){if(r.kind!=='facility')return [];const known=['보일러','도장','소각','발전','반도체','시멘트','유리','철강','비철금속','가스','섬유','고무','플라스틱','석유','기초유기화합물','기초무기화합물','화장','인쇄'];return known.filter(w=>norm(r.title).includes(norm(w))).slice(0,3)}
function openDetail(id){const r=byId.get(id);if(!r)return;if(r.kind==='standard'){openNumeric(r);return;}selected=r;selectedPage=r.page;$('#detail-kicker').textContent=`별표 ${r.annex} · ${r.kind==='facility'?'시설 분류 상세':'원문 페이지 열람'}`;const words=relatedWords(r);$('#detail-body').innerHTML=`<span class="badge ${r.annex===8?'standard':''}">${r.annex===3?'배출시설':'배출허용기준'}</span><h2 class="detail-heading">${esc(r.title)}</h2><div class="detail-meta">대기환경보전법 시행규칙 · 첨부본 개정 2025. 10. 1.<br>${r.eras.includes('past')&&!r.eras.includes('current')?'2019년 12월 31일까지 적용':'2020년 1월 1일부터 적용하는 기준 및 관련 비고'} · 원문 ${r.pages.join(', ')}쪽</div><div class="detail-actions"><button class="button secondary" data-save="${r.id}" aria-pressed="${saved.includes(r.id)}">${icon('bookmark')}${saved.includes(r.id)?'보관됨':'보관하기'}</button><a class="button secondary" href="${r.file}#page=${r.page}" target="_blank" rel="noopener">PDF 열기 ↗</a><button class="button secondary" id="share-record">링크 복사</button></div>${r.kind==='facility'?`<h3 class="detail-section-title">대상 및 규모 조건</h3><pre class="extracted">${highlight(r.text)}</pre><div class="notice">개별 시설 조건과 함께 적용기준(12–13쪽), 비고(27–29쪽)의 예외·규모 합산 조건을 확인하세요.</div><div class="detail-related"><button data-open="p3-12-current">적용기준 보기</button><button data-open="p3-27">비고 보기</button>${words.map(w=>`<button data-related="${esc(w)}">${esc(w)} 배출허용기준 검색 ↗</button>`).join('')}</div>`:`<div class="notice">표의 수치는 설치 시기·시설 규모·연료 및 비고와 함께 읽어야 합니다. 괄호 안 숫자 등 기호는 원문 비고에서 의미를 확인하세요.</div>${r.annex===8?'<div class="detail-related"><button data-open="p8-39">가스형태 비고</button><button data-open="p8-49">입자형태 비고</button></div>':''}`}<h3 class="detail-section-title">원문 그대로 보기</h3><p class="source-help">페이지를 넘겨 앞뒤 조건을 확인하세요. 이미지를 누르면 크게 열립니다.</p><div class="page-controls"><button id="prev-page" aria-label="원문 이전 페이지">← 이전</button><span id="page-label"></span><button id="next-page" aria-label="원문 다음 페이지">다음 →</button></div><a id="page-image-link" target="_blank" rel="noopener"><img id="page-image" class="page-image" alt=""></a><p id="image-error" class="source-help" hidden>원문 이미지를 불러오지 못했습니다. 연결을 확인하거나 위의 PDF 열기를 이용하세요.</p><details><summary>검색용 텍스트 보기</summary><p class="source-help">자동 추출 텍스트입니다. 표의 행·열 관계는 위 원문 이미지를 기준으로 확인하세요.</p><pre id="page-text" class="extracted"></pre></details>`;renderPage();if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;}
function renderPage(){const r=data.records.find(p=>p.annex===selected.annex&&p.page===selectedPage);const count=data.documents.find(d=>d.annex===selected.annex).count;$('#page-label').innerHTML=pageJumpMarkup('source',selectedPage,count,`별표 ${selected.annex} 원문 페이지`);$('#prev-page').disabled=selectedPage<=1;$('#next-page').disabled=selectedPage>=count;const img=$('#page-image');$('#image-error').hidden=true;img.onerror=()=>{$('#image-error').hidden=false};img.src=r.image;img.alt=`대기환경보전법 시행규칙 별표 ${selected.annex}, 원문 ${selectedPage}쪽`;$('#page-image-link').href=r.image;$('#page-text').textContent=data.records.filter(p=>p.annex===selected.annex&&p.page===selectedPage).map(p=>p.text).join('\n');}
function info(type){$('#info-body').innerHTML=type==='install'?`<span class="badge">웹 · 모바일</span><h2>에어코드를 홈 화면에</h2><p>브라우저에서 앱처럼 설치해 사용할 수 있습니다.</p><ol><li><strong>Android · PC</strong><br>Chrome 또는 Edge 메뉴에서 ‘앱 설치’ 또는 ‘홈 화면에 추가’를 선택하세요.</li><li><strong>iPhone · iPad</strong><br>Safari 공유 메뉴 → ‘홈 화면에 추가’를 선택하세요.</li></ol><p>설치 메뉴는 HTTPS 브라우저에서 지원됩니다. 오프라인에서는 저장된 검색 자료와 이전에 열어본 원문 이미지를 사용할 수 있습니다.</p>${deferredInstall?'<button class="button" id="native-install">이 기기에 설치</button>':''}`:`<span class="badge">검색 가이드</span><h2>찾고, 읽고, 확인하세요.</h2><ol><li><strong>오염물질 선택 후 시설명으로 검색</strong><br>‘보일러’, ‘질소산화물’, ‘NOx’처럼 입력하세요. 여러 단어는 모두 포함된 자료를 찾습니다.</li><li><strong>적용 시기와 자료 선택</strong><br>2020년 이후 기준이 기본입니다. 2019년까지 기준은 별도로 선택하세요.</li><li><strong>원문 표와 비고 확인</strong><br>기준값 옆의 단위·설치일·규모를 확인하세요. 관련 비고는 상세 화면에서 읽을 수 있고, PDF는 근거 확인용으로 접어두었습니다.</li></ol><p>보관함은 이 브라우저에 저장됩니다. 첨부본 개정일은 2025. 10. 1.이며, 현행 법령과의 일치 여부를 자동으로 갱신하지 않습니다.</p><button class="button" id="show-install-help">홈 화면에 앱 설치</button>`;$('#info-dialog').showModal()}
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.view){navigate(b.dataset.view);window.scrollTo(0,0)}if(b.dataset.query!==undefined)doSearch(b.dataset.query);if(b.dataset.open)openDetail(b.dataset.open);if(b.dataset.save)toggleSaved(b.dataset.save);if(b.hasAttribute('data-reset'))reset();if(b.dataset.related){$('#detail').close();navigate('standards',{q:b.dataset.related});window.scrollTo(0,0)}if(b.id==='prev-page'){selectedPage--;renderPage()}if(b.id==='next-page'){selectedPage++;renderPage()}if(b.id==='share-record'){const u=new URL(window.Capacitor?.isNativePlatform()?'https://todaynit1-sys.github.io/mamo-aircode/':location.href);u.hash=`search?record=${encodeURIComponent(selected.id)}`;try{await navigator.clipboard.writeText(u.href);toast('원문 항목 링크를 복사했습니다')}catch{toast('링크 복사가 지원되지 않습니다. 브라우저 주소를 복사하세요.')}}if(b.id==='show-install-help')info('install');if(b.id==='native-install'&&deferredInstall){await deferredInstall.prompt();deferredInstall=null;$('#info-dialog').close()}});
$('#search-form').addEventListener('submit',e=>{e.preventDefault();doSearch($('#query').value)});let debounce;$('#query').addEventListener('input',e=>{clearTimeout(debounce);debounce=setTimeout(()=>doSearch(e.target.value),180)});$$('input[name=source],input[name=era]').forEach(e=>e.addEventListener('change',()=>{if(e.name==='source'){source=e.value;if(source==='3')category='all';}else era=e.value;limit=8;syncFilters();render();urlState()}));$('#category').addEventListener('change',e=>{category=e.target.value;limit=8;render();urlState()});$('#sort').addEventListener('change',()=>render());$('#reset').onclick=reset;$('#load-more').onclick=()=>{limit+=8;render()};$('#close-detail').onclick=()=>$('#detail').close();$('#close-info').onclick=()=>$('#info-dialog').close();$('#help').onclick=()=>info('help');$('#install').onclick=()=>info('install');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#detail').open&&!$('#info-dialog').open){e.preventDefault();if(['saved','sources'].includes(view))navigate('search');$('#query').focus()}});
async function init(){try{const res=await fetch('data.json');if(!res.ok)throw Error('data');data=await res.json();const catalogResponse=await fetch('pollutants.json');if(!catalogResponse.ok)throw Error('catalog');pollutantCatalog=await catalogResponse.json();setupCatalog();allRecords=[...data.standards,...data.facilities,...data.records];setupNumeric();byId=new Map(allRecords.map(r=>[r.id,r]));saved=saved.filter(id=>byId.has(id));const [route,params='']=location.hash.slice(1).split('?'),p=new URLSearchParams(params);view=labels[route]?route:'standards';query=p.get('q')||'';source=['3','8','all'].includes(p.get('source'))?p.get('source'):view==='facilities'?'3':view==='standards'?'8':'all';era=['current','past','all'].includes(p.get('era'))?p.get('era'):'current';category=['가스','입자','비고','특례'].includes(p.get('type'))?p.get('type'):'all';navigate(view,{keep:true});if(p.get('record'))openDetail(p.get('record'));updateNumericControls();if('serviceWorker'in navigator&&!window.Capacitor?.isNativePlatform()&&location.protocol!=='capacitor:')navigator.serviceWorker.register('sw.js').catch(()=>{});registerTools();}catch(e){$('#results').innerHTML=`<div class="empty"><h3>자료를 불러오지 못했습니다</h3><p>인터넷 연결을 확인하고 다시 시도해 주세요.</p><button onclick="location.reload()">다시 불러오기</button></div>`;$('#result-count').textContent='불러오기 실패'}}
function registerTools(){if(!document.modelContext?.registerTool)return;try{Promise.resolve(document.modelContext.registerTool({name:'search_aircode',title:'대기환경 법령 검색',description:'첨부 별표의 검색 화면을 갱신하고 관련 원문 항목을 반환합니다. 적용 기준을 자동 확정하지 않습니다.',inputSchema:{type:'object',properties:{query:{type:'string'},source:{type:'string',enum:['all','3','8']}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.query!=='string'||input.query.length>300||input.source&&!['all','3','8'].includes(input.source))throw Error('Invalid search input');navigate('search',{q:input.query});source=input.source||'all';syncFilters();render();urlState();return filtered().slice(0,10).map(r=>({id:r.id,title:r.title,annex:r.annex,pages:r.pages,value:r.value,unit:r.unit,oxygen:r.oxygen,facility:r.facility,conditions:r.conditions,regime:r.regime,revision:data.revision}));}})).catch(()=>{})}catch{}}
$('.brand').addEventListener('click',e=>{e.preventDefault();navigate('search')});
init();
