'use strict';
let groupSignature='',groupPage=0,openGroup=null,rowPage=0;
const groupDesktop=matchMedia('(min-width:1100px)'),ROW_PAGE_SIZE=6;
let GROUP_PAGE_SIZE=groupDesktop.matches?12:6;
groupDesktop.addEventListener('change',e=>{const anchor=openGroup??groupPage*GROUP_PAGE_SIZE;GROUP_PAGE_SIZE=e.matches?12:6;groupPage=Math.floor(anchor/GROUP_PAGE_SIZE);if(document.querySelector('#results.grouped-results'))render()});
function groupStandards(records){const groups=new Map();for(const r of records){const key=JSON.stringify([r.pollutant,norm(r.facility),r.regime,r.unit]);if(!groups.has(key))groups.set(key,{...r,rows:[]});groups.get(key).rows.push(r)}return [...groups.values()]}
function groupRange(g){const values=g.rows.map(r=>Number(r.value));if(values.some(v=>!Number.isFinite(v)))return esc(g.rawValue);const low=Math.min(...values),high=Math.max(...values);return `${low===high?low:low+'–'+high} <small>${esc(g.unit)}</small>`}
function groupPager(page,total,attribute,label){return total>1?`<nav class="group-pager" aria-label="${label}"><button ${attribute}="${page-1}" ${page===0?'disabled':''} aria-label="${label} 이전">← 이전</button>${pageJumpMarkup(attribute==='data-group-page'?'group':'row',page+1,total,label)}<button ${attribute}="${page+1}" ${page===total-1?'disabled':''} aria-label="${label} 다음">다음 →</button></nav>`:''}
function groupedRow(r){return `<div class="criteria-row" data-record-id="${r.id}"><div class="criteria-conditions">${r.conditions.length?r.conditions.map(c=>`<div>${highlight(c)}</div>`).join(''):'추가 시설 구분 없음'}</div><div class="criteria-value"><button data-open="${r.id}" aria-label="${esc(r.pollutant+' '+r.rawValue)} 조건 상세"><strong>${r.pollutant==='매연'?'2도 또는 40%':esc(r.value)}</strong><span>${r.pollutant==='매연'?'링겔만도 / 불투명도':esc(r.unit)} 이하</span></button><small>표준 O₂ ${r.oxygen===null?'별도 표기 없음':esc(r.oxygen)+'%'}</small><div class="criteria-actions"><button data-open="${r.id}">상세 ↗</button><button data-save="${r.id}" aria-label="기준 ${saved.includes(r.id)?'보관 해제':'보관'}" aria-pressed="${saved.includes(r.id)}">${saved.includes(r.id)?'보관됨':'보관'}</button></div></div></div>`}
function renderGroupedStandards(results){$('#results').classList.remove('grouped-results');if(!results.length||results.some(r=>r.kind!=='standard')){groupSignature='';return false}const signature=JSON.stringify([query,source,era,category,pollutantFilter,regimeFilter,$('#sort').value,results.map(r=>r.id)]);if(signature!==groupSignature){groupSignature=signature;groupPage=0;openGroup=null;rowPage=0}$('#results').classList.add('grouped-results');const groups=groupStandards(results),pages=Math.ceil(groups.length/GROUP_PAGE_SIZE);groupPage=Math.min(groupPage,pages-1);$('#result-count').textContent=`시설 ${groups.length}개 · 조건 ${results.length}개`;$('#load-more').hidden=true;$('#results').innerHTML=`${groups.slice(groupPage*GROUP_PAGE_SIZE,(groupPage+1)*GROUP_PAGE_SIZE).map((g,i)=>{const index=groupPage*GROUP_PAGE_SIZE+i,expanded=openGroup===index;return `<article class="facility-group ${expanded?'is-expanded':''}"><button class="group-toggle" data-group-toggle="${index}" aria-expanded="${expanded}" aria-controls="group-panel-${index}"><span class="group-info"><span class="group-meta">${esc(g.pollutant)} ${catalogBadge(g.pollutant)} <span>· 조건 ${g.rows.length}개${g.regime==='annual10'?' · 연간 10톤 이상 별도 기준':''}</span></span><strong>${highlight(g.facility)}</strong></span><span class="group-range"><b>${groupRange(g)}</b><small>${g.rows.length>1?'조건별 범위':'기준값 이하'}</small></span><span class="group-chevron" aria-hidden="true">${expanded?'−':'＋'}</span></button><div id="group-panel-${index}" class="group-panel" ${expanded?'':'hidden'}>${expanded?`<p class="group-caption">${numericScope(g)} · 각 행의 시설 조건과 표준산소농도를 함께 확인하세요.</p>${g.rows.slice(rowPage*ROW_PAGE_SIZE,(rowPage+1)*ROW_PAGE_SIZE).map(groupedRow).join('')}${groupPager(rowPage,Math.ceil(g.rows.length/ROW_PAGE_SIZE),'data-row-page','시설 내 조건 페이지')}`:''}</div></article>`}).join('')}${groupPager(groupPage,pages,'data-group-page','시설 목록 페이지')}`;return true}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-group-toggle')){const index=Number(b.dataset.groupToggle);openGroup=openGroup===index?null:index;rowPage=0;render();document.querySelector(`[data-group-toggle="${index}"]`)?.focus({preventScroll:true})}if(b.hasAttribute('data-group-page')){groupPage=Number(b.dataset.groupPage);openGroup=null;rowPage=0;render();$('#result-heading').scrollIntoView({block:'start'});document.querySelector('.group-toggle')?.focus({preventScroll:true})}if(b.hasAttribute('data-row-page')){rowPage=Number(b.dataset.rowPage);render();const panel=document.querySelector(`#group-panel-${openGroup}`);panel?.scrollIntoView({block:'start'});panel?.querySelector('[data-open]')?.focus({preventScroll:true})}});
