'use strict';
// PDF.js is imported only after the reader opens a visual preview.
window.MethodPreview=(()=>{
 let libraryPromise=null,current=null;
 const asset=path=>new URL('vendor/pdfjs/'+path,document.baseURI).href;
 function library(){if(!libraryPromise)libraryPromise=import(asset('pdf.min.mjs')).then(lib=>{lib.GlobalWorkerOptions.workerSrc=asset('pdf.worker.min.mjs');return lib}).catch(e=>{libraryPromise=null;throw e});return libraryPromise}
 function figures(doc){return doc.pages.flatMap(p=>p.text.split('\n').map(t=>t.trim()).filter(t=>/^그림\s*\d+(?:[.-]\d+)*[.\s]/.test(t)).map(title=>({page:p.page,title})));}
 function markup(r,doc){const list=figures(doc),pages=new Set(list.map(x=>x.page));return `<section class="method-visual-section" aria-label="그림과 원문 페이지"><div class="method-visual-heading"><strong>그림도 원문 그대로</strong><p>채취장치 그림·표·수식을 앱 안에서 확대해 보세요.</p></div>${list.length?`<details class="method-figure-index"><summary>그림 목차 <span>${list.length}개</span></summary><div>${list.map(f=>`<button data-preview-page="${f.page}"><span>${esc(f.title)}</span><small>${f.page}쪽 →</small></button>`).join('')}</div></details>`:''}<details id="method-visual" class="method-visual"><summary>그림·표·수식 원문 보기 <span>펼치기</span></summary><div class="method-visual-content"><div class="method-page-nav"><button type="button" data-preview-prev aria-label="그림 원문 이전 페이지">← 이전</button><label><span class="preview-sr">원문 페이지 선택</span><select id="preview-page" aria-label="원문 페이지 선택">${doc.pages.map(p=>`<option value="${p.page}">${p.page} / ${r.pages}쪽${pages.has(p.page)?' · 그림':''}</option>`).join('')}</select></label><button type="button" data-preview-next aria-label="그림 원문 다음 페이지">다음 →</button></div><div class="method-zoom"><span>확대해서 자세히 보기</span><button type="button" data-preview-minus aria-label="원문 축소">−</button><output id="preview-zoom">100%</output><button type="button" data-preview-plus aria-label="원문 확대">＋</button><button type="button" data-preview-fit>맞춤</button></div><p class="method-visual-hint">확대 후 그림을 좌우로 밀어 보세요. 휴대폰 화면 자체의 확대도 사용할 수 있습니다.</p><p id="preview-status" role="status" aria-live="polite"></p><button type="button" class="button secondary" data-preview-retry hidden>다시 불러오기</button><div id="preview-scroll" class="method-canvas-scroll" tabindex="0" aria-label="확대된 원문, 좌우로 스크롤"><div id="preview-canvas"></div></div><a id="preview-original" href="${r.file}#page=1" target="_blank" rel="noopener">PDF에서 이 페이지 열기 ↗</a><p class="method-visual-footnote">보기 버튼을 누를 때 해당 PDF와 뷰어를 불러옵니다. 원본 문서를 화면에 그려 표시합니다.</p></div></details></section>`}
 function live(s){return current===s&&s.host.isConnected&&!s.disposed}
 function dispose(){const s=current;current=null;if(!s)return;s.disposed=true;clearTimeout(s.resizeTimer);s.observer?.disconnect();s.task?.cancel();s.loading?.destroy().catch(()=>{});s.host.querySelectorAll('canvas').forEach(c=>{c.width=0;c.height=0});}
 async function documentFor(s){if(!s.documentPromise)s.documentPromise=(async()=>{const lib=await library();if(!live(s))throw Error('closed');s.loading=lib.getDocument({url:new URL(s.record.file,document.baseURI).href,disableRange:true,disableStream:true,isEvalSupported:false,standardFontDataUrl:asset('standard_fonts/'),wasmUrl:asset('wasm/')});return s.loading.promise})().catch(e=>{s.documentPromise=null;throw e});return s.documentPromise}
 function controls(s){s.host.querySelector('#preview-page').value=String(s.page);s.host.querySelector('[data-preview-prev]').disabled=s.page<=1;s.host.querySelector('[data-preview-next]').disabled=s.page>=s.record.pages;s.host.querySelector('[data-preview-minus]').disabled=s.zoom<=1;s.host.querySelector('[data-preview-plus]').disabled=s.zoom>=2.5;s.host.querySelector('#preview-zoom').textContent=Math.round(s.zoom*100)+'%';s.host.querySelector('#preview-original').href=s.record.file+'#page='+s.page;}
 async function draw(s){if(!live(s)||!s.host.open)return;const token=++s.token;s.task?.cancel();controls(s);const status=s.host.querySelector('#preview-status'),holder=s.host.querySelector('#preview-canvas'),scroll=s.host.querySelector('#preview-scroll');status.textContent=`${s.page}쪽 원문을 불러오는 중…`;scroll.setAttribute('aria-busy','true');s.host.querySelector('[data-preview-retry]').hidden=true;holder.replaceChildren();try{const pdf=await documentFor(s);if(!live(s)||token!==s.token)return;const page=await pdf.getPage(s.page);if(!live(s)||token!==s.token)return;const width=Math.max(180,scroll.clientWidth-2),natural=page.getViewport({scale:1}),viewport=page.getViewport({scale:width/natural.width*s.zoom}),ratio=Math.min(window.devicePixelRatio||1,2,2400/viewport.width);const canvas=document.createElement('canvas');canvas.setAttribute('role','img');canvas.setAttribute('aria-label',`${s.record.code} ${s.page}쪽 원문 그림·표·수식. 같은 페이지의 텍스트는 아래 본문에서 읽을 수 있습니다.`);canvas.width=Math.floor(viewport.width*ratio);canvas.height=Math.floor(viewport.height*ratio);canvas.style.width=Math.floor(viewport.width)+'px';canvas.style.height=Math.floor(viewport.height)+'px';holder.append(canvas);s.task=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:ratio!==1?[ratio,0,0,ratio,0,0]:null});await s.task.promise;if(!live(s)||token!==s.token)return;scroll.setAttribute('aria-busy','false');status.textContent=`${s.page} / ${s.record.pages}쪽 · 원문 표시 완료`;scroll.scrollLeft=0;}catch(e){if(!live(s)||token!==s.token||e.name==='RenderingCancelledException')return;scroll.setAttribute('aria-busy','false');status.textContent='원문 미리보기를 불러오지 못했습니다. 다시 시도하거나 아래 PDF 링크를 이용하세요.';s.host.querySelector('[data-preview-retry]').hidden=false;}}
 function showPage(page){const s=current;if(!s||!live(s))return;s.page=Math.max(1,Math.min(s.record.pages,Number(page)||1));s.zoom=1;const wasOpen=s.host.open;s.host.open=true;if(wasOpen)draw(s);s.host.scrollIntoView({behavior:'smooth',block:'start'});}
 function mount(r){const host=document.getElementById('method-visual');if(!host)return;const s=current={host,record:r,page:1,zoom:1,token:0,disposed:false};controls(s);host.addEventListener('toggle',()=>{if(host.open)draw(s);else{s.token++;s.task?.cancel();}});host.querySelector('#preview-page').onchange=e=>{s.page=Number(e.target.value);draw(s)};host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-preview-prev'))s.page=Math.max(1,s.page-1);else if(b.hasAttribute('data-preview-next'))s.page=Math.min(r.pages,s.page+1);else if(b.hasAttribute('data-preview-plus'))s.zoom=Math.min(2.5,s.zoom+.5);else if(b.hasAttribute('data-preview-minus'))s.zoom=Math.max(1,s.zoom-.5);else if(b.hasAttribute('data-preview-fit'))s.zoom=1;else if(!b.hasAttribute('data-preview-retry'))return;draw(s)});if('ResizeObserver'in window){let width=0;s.observer=new ResizeObserver(entries=>{const next=Math.round(entries[0].contentRect.width);if(next===width)return;width=next;clearTimeout(s.resizeTimer);s.resizeTimer=setTimeout(()=>draw(s),150)});s.observer.observe(host.querySelector('#preview-scroll'));}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-preview-page]');if(b)showPage(b.dataset.previewPage)});
 document.addEventListener('DOMContentLoaded',()=>document.getElementById('detail').addEventListener('close',dispose));
 return {markup,mount,dispose};
})();
