'use strict';
let methodIndex, methodLoading, methodLimit=12, methodRequest=0;
const methodParams=new URLSearchParams(location.hash.split('?')[1]||'');
let methodQuery=methodParams.get('mq')||'',methodGroup=methodParams.get('mg')||'all';
async function loadMethods(){if(methodIndex)return methodIndex;if(!methodLoading)methodLoading=fetch('methods-index.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>methodIndex=x).catch(e=>{methodLoading=null;throw e});return methodLoading}
function methodSearchText(s){return norm(s).replace(/스틸렌/g,'스타이렌').replace(/시안화수소/g,'사이안화수소').replace(/크롬/g,'크로뮴').replace(/염화비닐/g,'염화바이닐').replace(/클로로포름/g,'클로로폼').replace(/부타디엔/g,'뷰타다이엔').replace(/디클로로메탄/g,'다이클로로메테인').replace(/디클로로에탄/g,'다이클로로에테인').replace(/트리클로로/g,'트라이클로로').replace(/아크릴로니트릴/g,'아크릴로나이트릴').replace(/염소/g,'클로린').replace(/불소/g,'플루오린').replace(/브롬/g,'브로민').replace(/포름알데히드/g,'폼알데하이드').replace(/및그화합물|화합물/g,'')}
function methodUrl(){const p=new URLSearchParams();if(methodQuery)p.set('mq',methodQuery);if(methodGroup!=='all')p.set('mg',methodGroup);history.replaceState(null,'','#methods'+(p.toString()?'?'+p:''))}
async function renderMethods(){const host=$('#methods-view');host.innerHTML='<p role="status">시험방법 목록을 불러오는 중…</p>';try{await loadMethods();if(view!=='methods')return;host.innerHTML=`<div class="method-intro"><strong>공정시험기준 <b>${methodIndex.length}</b>개</strong><span>ES 번호 · 물질 · 시험방법으로 검색</span></div><div class="method-controls"><input id="method-query" type="search" aria-label="시험방법 검색" placeholder="예: 먼지, ES 01301, 기체크로마토그래피" value="${esc(methodQuery)}"><select id="method-group" aria-label="시험방법 분류"><option value="all">모든 분류</option>${[...new Set(methodIndex.map(x=>x.group))].map(g=>`<option ${g===methodGroup?'selected':''}>${esc(g)}</option>`).join('')}</select></div><details class="method-guidance"><summary>수록 문서와 적용 안내</summary><p>제공된 공정시험기준 160개를 수록했습니다. 표기 연도는 개별 문서 첫 페이지 기준입니다. 같은 물질도 측정 방식과 적용범위가 다르므로 시험방법의 적용범위를 확인하세요.</p><p>텍스트는 원문에서 자동 추출했습니다. 수식·표·그림은 상세 화면의 원문 보기에서 확대할 수 있습니다. 뷰어를 열 때 해당 PDF만 불러옵니다.</p><a href="https://www.law.go.kr/admRulSc.do?query=대기오염공정시험기준" target="_blank" rel="noopener">현행 고시 확인 ↗</a></details><div class="method-result-meta" id="method-count" role="status"></div><div id="method-list" class="method-list"></div><button id="method-more" class="load-more">더 보기</button>`;$('#method-query').oninput=e=>{methodQuery=e.target.value;methodLimit=12;renderMethodList();methodUrl()};$('#method-group').onchange=e=>{methodGroup=e.target.value;methodLimit=12;renderMethodList();methodUrl()};$('#method-more').onclick=()=>{methodLimit+=12;renderMethodList()};renderMethodList();methodUrl();if(methodParams.get('method')){const id=methodParams.get('method');methodParams.delete('method');openMethod(id)}}catch{if(view==='methods')host.innerHTML='<p>목록을 불러오지 못했습니다. 연결을 확인한 뒤 다시 시도하세요.</p><button class="button" data-view="methods">다시 시도</button>'}}
function renderMethodList(){const terms=methodQuery.trim().split(/\s+/).filter(Boolean).map(methodSearchText);const rows=methodIndex.filter(r=>(methodGroup==='all'||r.group===methodGroup)&&terms.every(t=>methodSearchText(r.code+' '+r.title).includes(t)));$('#method-count').textContent=`${rows.length}개 시험방법 · ${Math.min(methodLimit,rows.length)}개 표시`;$('#method-list').innerHTML=rows.slice(0,methodLimit).map(r=>`<button class="method-card" data-method="${r.id}"><span class="method-code">${esc(r.code)} <small>${esc(r.group)}</small></span><strong>${esc(r.title)}</strong><span class="method-meta">${r.year?'문서 표기 '+esc(r.year)+'년 · ':''}${r.pages}쪽 <span>내용 보기 →</span></span></button>`).join('')||'<div class="empty"><h3>일치하는 시험방법이 없습니다</h3><p>물질명을 짧게 입력하거나 모든 분류로 변경하세요.<br>검색 결과 없음은 시험방법이 없다는 의미가 아닙니다.</p></div>';$('#method-more').hidden=rows.length<=methodLimit}
async function openMethod(id){MethodPreview.dispose();const request=++methodRequest;await loadMethods();const r=methodIndex.find(x=>x.id===id);if(!r)return;$('#detail-kicker').textContent='공정시험기준 · '+r.code;$('#detail-body').innerHTML=`<h2 class="detail-heading">${esc(r.title)}</h2><p class="detail-meta">${esc(r.code)} · ${r.year?'문서 표기 '+esc(r.year)+'년 · ':''}${r.pages}쪽</p><div class="detail-actions"><a class="button" href="${r.file}" target="_blank" rel="noopener">PDF 원문 열기 ↗</a><button class="button secondary" id="method-copy">링크 복사</button></div><p class="source-help">자동 추출 텍스트입니다. 그림·표·수식은 아래 원문 보기에서 확대해 확인하세요.</p><div id="method-text" role="status">문서 내용을 불러오는 중…</div>`;if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;$('#method-copy').onclick=async()=>{const u=new URL('https://todaynit1-sys.github.io/mamo-aircode/');u.hash='methods?method='+id;try{await navigator.clipboard.writeText(u.href);toast('시험방법 링크를 복사했습니다')}catch{toast('링크 복사를 지원하지 않는 브라우저입니다')}};try{const res=await fetch(r.textFile);if(!res.ok)throw Error();const doc=await res.json();if(request!==methodRequest)return;$('#method-text').innerHTML=MethodPreview.markup(r,doc)+`<div class="text-jump-row"><span>본문 페이지 바로가기</span>${pageJumpMarkup('text',1,r.pages,'본문 페이지')}</div>`+doc.pages.map((p,i)=>`<details class="method-page" data-text-page="${p.page}" ${i===0?'open':''}><summary>${p.page}쪽 · ${i===0?'개요 및 적용범위':'본문'}</summary><button class="button secondary method-page-preview" data-preview-page="${p.page}">이 페이지 그림·표 보기</button><pre>${esc(p.text)}</pre><a href="${r.file}#page=${p.page}" target="_blank" rel="noopener">이 페이지 원문 ↗</a></details>`).join('');MethodPreview.mount(r)}catch{if(request===methodRequest&&$('#method-text'))$('#method-text').textContent='텍스트를 불러오지 못했습니다. PDF 원문을 이용하세요.'}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.method)openMethod(b.dataset.method);if(b.dataset.testSearch!==undefined){$('#detail').close();methodQuery=b.dataset.testSearch;methodGroup='all';methodLimit=12;navigate('methods');window.scrollTo(0,0)}});

