'use strict';
let pollutantCatalog=[],catalogTab=1,catalogQuery='',catalogLink=null;
const catalogAlias={'입자상물질':['먼지','비산먼지','매연'],'시안화물':['시안화수소'],'염소및그화합물':['염화수소'],'염소및염화수소':['염화수소'],'불소화물':['불소화합물'],'브롬및그화합물':['브롬화합물']};
function catalogTargets(name){const key=norm(name);if(catalogAlias[key])return catalogAlias[key].filter(n=>data.standards.some(r=>r.pollutant===n));const simplified=key.replace('및그화합물','화합물');return [...new Set(data.standards.filter(r=>norm(r.pollutant)===key||norm(r.pollutant)===simplified).map(r=>r.pollutant))]}
function linkedCatalogItem(){if(!catalogLink)return null;const [annex,number]=catalogLink.split('-').map(Number);return pollutantCatalog.find(d=>d.annex===annex)?.items.find(i=>i.number===number)||null}
function catalogBadge(name){return pollutantCatalog.find(d=>d.annex===2)?.items.some(i=>catalogTargets(i.name).includes(name))?'<span class="hazard-badge">특정대기유해물질</span>':''}
function renderCatalog(){const doc=pollutantCatalog.find(d=>d.annex===catalogTab);if(!doc)return;const needle=norm(aliases[catalogQuery.toLowerCase()]||catalogQuery);const rows=doc.items.filter(i=>norm(i.name).includes(needle)||catalogTargets(i.name).some(n=>norm(n).includes(needle)));$('#catalog-count').textContent=`${rows.length}개 물질`;$('#catalog-list').innerHTML=rows.length?rows.map(i=>{const targets=catalogTargets(i.name),count=data.standards.filter(r=>targets.includes(r.pollutant)).length;return `<button class="catalog-item" data-catalog-go="${doc.annex}-${i.number}"><span class="catalog-number">${String(i.number).padStart(2,'0')}</span><span><strong>${esc(i.name)}</strong><small>${count?`기준 ${count}개`:'등록 수치 없음 · 안내'}</small></span></button>`}).join(''):'<p class="empty">일치하는 물질이 없습니다.</p>';$('#catalog-proof').innerHTML=`<a href="${doc.file}" target="_blank" rel="noopener">별표 ${doc.annex} 원문 확인 ↗</a><span>${doc.revision?'첨부본 개정 '+doc.revision:'첨부본에 별도 개정일 표기 없음'}</span>`;$$('[data-catalog-tab]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.catalogTab)===catalogTab));$('.document-count').innerHTML=`<strong>${doc.items.length}</strong><span>${catalogTab===1?'대기오염물질':'특정대기유해물질'}<small>첨부 별표 ${catalogTab} 기준</small></span>`}
function updateCatalogLink(){let banner=$('#catalog-link-note');if(!banner){banner=document.createElement('div');banner.id='catalog-link-note';banner.className='catalog-link-note';$('#numeric-toolbar').prepend(banner)}const item=linkedCatalogItem();banner.hidden=!item;if(item){const names=catalogTargets(item.name);banner.innerHTML=`<strong>${esc(item.name)}</strong><p>${names.length?'관련 기준: '+names.map(esc).join(' · '):'이 물질에 연결된 수치 기준은 현재 앱에 등록되어 있지 않습니다. 배출허용기준이 없거나 규제 대상이 아니라는 의미는 아닙니다. 원문 자료실과 해당 규정을 확인하세요.'}</p><button data-view="pollutants">← 물질 목록</button><button data-clear-catalog>연결 조건 해제</button>`}}
function setupCatalog(){const p=new URLSearchParams(location.hash.split('?')[1]||'');catalogLink=p.get('catalog');if(!linkedCatalogItem())catalogLink=null;$('#catalog-query').oninput=e=>{catalogQuery=e.target.value;renderCatalog()};document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-catalog-tab')){catalogTab=Number(b.dataset.catalogTab);renderCatalog()}if(b.dataset.catalogGo){navigate('standards');catalogLink=b.dataset.catalogGo;regimeFilter='all';$('#regime').value='all';render();urlState();window.scrollTo(0,0)}if(b.hasAttribute('data-clear-catalog')){catalogLink=null;render();urlState()}})}
